version: '3'

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "7000:55432"
    networks:
      - etl_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:latest
    ports:
      - "7001:55433"
    networks:
      - etl_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret    

  elt_script:
    build:
      context: ./elt/
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - etl_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  etl_network:
    driver: bridge